apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: guhanandan/node-userapp:v1.0.3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-svc
spec:
  selector:
    app: employee-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
